.gitignore, lib/jadeCompiler.js, lib/mailer.js, package.json, public/sass/elements/confirmation-box.scss, public/sass/style.scss, routes/enquiry-form.js, views/emails/inward-enquiry.jade, views/enquiry-form.jade, views/enquiry-success.jade, views/error.jade, views/index.jade, views/layout.jade
Add support to send data submitted to form via email. SMTP details are stored in environment variables.
=> Send email

app.js, package.json, public/javascripts/main.js, public/javascripts/modules/autocomplete.js, public/javascripts/plugins/autocomplete.noResults.js, public/sass/elements/autocomplete.scss, public/sass/style.scss, routes/enquiry-form.js, views/enquiry-form.jade, views/includes/+form-elements.jade, webpack.config.js
- Refactor forms to use mixins
- Add autocomplete element for country and industry selectors
- Keep submitted form data when errors are triggered
- Add error summary
=> No selects

.istanbul.yml, README.md, package.json
Add reports for checking code coverage.
=> Add code coverage for JS

.jshintrc, app.js, apps/common/views/layout.html, assets/js/.eslintrc, assets/js/index.js, assets/js/modules/analytics.js, assets/js/modules/typeahead.js, assets/js/modules/validation-tracking.js, config.js, test/unit/apps/common/models/email.js
- Add analytics object to send event tracking
- Track form errors by field and message
=> Add event tracking for form validation

apps/common/fields/contact-details.js, apps/common/views/layout.html, apps/contact-ukti/views/personal-details.html, assets/scss/_shame.scss, assets/scss/app.scss, assets/scss/design-patterns/_alerts.scss, assets/scss/design-patterns/_autocomplete.scss, assets/scss/design-patterns/_icons.scss, assets/scss/design-patterns/_steps.scss, assets/scss/design-patterns/_table-details.scss, assets/scss/design-patterns/_validation.scss
* Fix SCSS style warnings
* Refactor sass to be more modular and maintainable
=> Refactor sass to be more maintainable

apps/common/controllers/confirm.js, apps/contact-ukti/fields/enquiry-reason.js, lib/analytics.js, package.json
Adds more analytics in the form of Google analytics.
This is a part time measure whilst there is no better way of tracking enquiry types.
Tracks:
* Type of enquiry
* Length of enquiry description
=> Track type of enquiry and description count

apps/contact-ukti/fields/enquiry.js, apps/contact-ukti/translations/src/en/fields.json, apps/contact-ukti/translations/src/en/validation.json, apps/contact-ukti/views/confirm.html, services/email/index.js, services/email/templates/contact-ukti/_data-html.jade, services/email/templates/contact-ukti/_data-text.jade
* Update instructions for enquiry reason to attempt to limit characters
* Make sure the 'other' reason is being displayed on the check your answers page
=> Enquiry details

apps/common/fields/contact-details.js, apps/common/fields/organisation-details.js, apps/common/fields/personal-details.js, apps/contact-ukti/fields/company-location.js, apps/contact-ukti/fields/data-protection.js, apps/contact-ukti/fields/enquiry-reason.js, apps/contact-ukti/fields/exported-before.js, apps/contact-ukti/fields/sector.js
Fix the content of some incorrect labels and remove unnecessary label definitions in the fields object.
=> Fix label definitions

app.js, config.js, documentation/ENVIRONMENT_VARIABLES.md, errors/index.js, package.json
Add ability to log errors in [sentry](https://getsentry.com).
=> Sentry error logging

apps/contact-ukti/controllers/personal-details.js, apps/contact-ukti/steps.js, apps/contact-ukti/views/enquiry.html, test/acceptance/features/company-address.feature, test/acceptance/features/company-details.feature, test/acceptance/features/company-location.feature, test/acceptance/features/confirm.feature, test/acceptance/features/enquiry-reason.feature, test/acceptance/features/enquiry.feature, test/acceptance/features/exported-before.feature, test/acceptance/features/industry.feature, test/acceptance/features/personal-details.feature, test/acceptance/features/steps/shared.js, test/acceptance/features/support/utils.js, test/unit/apps/contact-ukti/controllers/company-details.js, test/unit/apps/contact-ukti/controllers/company-location.js, test/unit/apps/contact-ukti/controllers/personal-details.js
Fix issues with back navigation
=> Back links

app.js, apps/common/views/cookies.html, apps/common/views/layout.html, apps/common/views/terms.html
Update the legal copy to match this service and department.
=> Update cookies and terms copy

.travis.yml, app.js
As a starting point, get tests running on Travis and feeding back to Pull Requests.
=> Run unit and integration tests on CI

app.js, apps/common/translations/src/en/errors.json, errors/page-not-found.js, lib/analytics.js
This adds support to handle pages that don't exist and display the generic error template.
=> Add page not found error handler

app.js
The previous implementation was creating a new session store PER request!
This creates one store for the middleware.
See similar BRP app [pull request](https://github.com/UKHomeOffice/brp_app/pull/329) for more details.
=> Fix memory leak with session creation

app.js, apps/common/fields/organisation-details.js, apps/common/translations/src/en/emails.json, apps/common/translations/src/en/errorlist.json, apps/common/translations/src/en/fields.json, apps/common/translations/src/en/footer.json, apps/common/views/cookies.html, apps/common/views/partials/navigation.html, apps/common/views/partials/validation-summary.html, apps/common/views/terms.html, apps/contact-ukti/fields/enquiry-reason.js, apps/contact-ukti/fields/enquiry.js, apps/contact-ukti/fields/sector.js, apps/contact-ukti/translations/src/en/emails.json, apps/contact-ukti/translations/src/en/fields.json, apps/contact-ukti/translations/src/en/pages.json, apps/contact-ukti/translations/src/en/validation.json, apps/contact-ukti/views/operating-industry.html, services/email/index.js, test/acceptance/features/confirm.feature, test/acceptance/features/pages/enquiry-reason.js, test/acceptance/features/steps/shared.js, test/unit/services/email/index.js
Includes copy amends based on feedback from content designer. 
In summary:
- Page headings
- Validation summary
- Field labels/options
- Data protection
- Confirmation page
- Terms & conditions page
- Cookie page
- Email copy
=> Copy amends

apps/common/controllers/confirm.js, apps/contact-ukti/fields/org-type.js, apps/contact-ukti/steps.js, apps/contact-ukti/translations/src/en/fields.json, apps/contact-ukti/translations/src/en/validation.json, apps/contact-ukti/views/confirm.html, apps/contact-ukti/views/organisation-type.html, services/email/templates/contact-ukti/_data-html.jade, services/email/templates/contact-ukti/_data-text.jade
This adds the ability to select what type of 'organisation' you are if you don't fit.
This also captures custom results to analytics to see if there are any patterns.
=> Add 'other' option for org type and capture results in analytics

package.json
Upgrade HOF to latest version.
=> Bump hof to v3.1.0

apps/contact-ukti/fields/exported-before.js, apps/contact-ukti/translations/src/en/emails.json, apps/contact-ukti/translations/src/en/fields.json, apps/contact-ukti/translations/src/en/pages.json, apps/contact-ukti/translations/src/en/validation.json, apps/contact-ukti/views/confirm.html, services/email/templates/contact-ukti/_data-html.jade, services/email/templates/contact-ukti/_data-text.jade, test/acceptance/features/pages/exported-before.js
Improve consistency in question answering by improving the language used.
=> Update copy and improve consistency in question language

app.js, apps/common/views/partials/page-header.html, apps/contact-ukti/views/confirmation.html, apps/office-finder/index.js, apps/office-finder/translations/src/en/fields.json, apps/office-finder/translations/src/en/pages.json, apps/office-finder/translations/src/en/validation.json, apps/office-finder/views/office-finder.html, apps/office-finder/views/partials/office.html, assets/data/regional-offices/East Midlands.yml, assets/data/regional-offices/East of England.yml, assets/data/regional-offices/London.yml, assets/data/regional-offices/North East.yml, assets/data/regional-offices/North West.yml, assets/data/regional-offices/Northern Ireland.yml, assets/data/regional-offices/South East.yml, assets/data/regional-offices/South West.yml, assets/data/regional-offices/Wales.yml, assets/data/regional-offices/West Midlands.yml, assets/data/regional-offices/Yorkshire and the Humber.yml, assets/scss/_shame.scss, assets/scss/app.scss, assets/scss/design-patterns/_office.scss, assets/scss/design-patterns/_panel.scss, package.json
Add a region finder sub app to the contact application.
=> Nearest region

apps/common/translations/src/en/buttons.json, apps/office-finder/translations/src/en/fields.json, apps/office-finder/views/office-finder.html, assets/scss/_shame.scss
* Improve button position on mobile
* Use more sensible button label
=> Office finder improvements

app.js
Redirect main URLs for legacy application.
**Main URLs to handle:**
* /uktihome/contactus/contactusform.html
* /[localisation]/uktihome/contactus/contactusform.html
* /uktihome/contactus/contactusform/thankyou.html
* /uktihome/contactus/investmentcontactusform.html
* /[localisation]/uktihome/contactus/investmentcontactusform.html
* /uktihome/contactus/investmentcontactusform/thankyou.html
* /[localisation]/uktihome/export/contactus/greatcontactusform.html
=> Handle legacy application redirects

apps/common/controllers/confirm.js, apps/common/models/email.js, apps/common/translations/src/en/emails.json, apps/contact-ukti/translations/src/en/pages.json, apps/contact-ukti/views/confirmation.html, assets/scss/app.scss, assets/scss/design-patterns/_confirmation-panel.scss, lib/reference-generator.js, package.json, services/email/index.js, services/email/templates/contact-ukti/_data-html.jade, services/email/templates/contact-ukti/_data-text.jade, services/email/templates/contact-ukti/caseworker/html.jade, services/email/templates/contact-ukti/caseworker/text.jade, services/email/templates/contact-ukti/customer/html.jade, services/email/templates/contact-ukti/customer/text.jade, services/email/templates/layouts/html.jade, test/unit/apps/common/controllers/confirm.js, test/unit/apps/common/models/email.js, test/unit/lib/reference-generator.js
This adds a reference number to the enquiry which allows staff handling them to track their progress and check back on old enquiries.
=> Create and replay reference number on screen and in emails

apps/common/fields/contact-details.js, apps/contact-ukti/steps.js, apps/contact-ukti/translations/src/en/fields.json, apps/contact-ukti/translations/src/en/validation.json, apps/contact-ukti/views/personal-details.html, test/acceptance/features/pages/personal-details.js
Allow users to choose their preferred contact method rather than
showing both with one being optional
=> Update contact preferences

apps/contact-ukti/fields/company-location.js, assets/countries/index.js, assets/js/modules/typeahead.js, assets/scss/design-patterns/_autocomplete.scss, assets/scss/design-patterns/_validation.scss
This improves the autocomplete functionality. 
Firstly, it shows a message when there are no results. Some users look at the keyboard whilst typing so this will signal something is wrong. 
It also removes the UK from the "Outside the UK" country options to avoid confusion.
=> Autocomplete

apps/common/views/layout.html
=> CU-7 Update feedback email subject

.eslintrc, .gitignore, app.js, apps/common/controllers/confirm.js, apps/common/views/terms.html, apps/contact-ukti/translations/src/en/fields.json, package.json, services/email/templates/layouts/html.jade
Also add some more useful logging
=> Replace remaining UKTI references to DIT

assets/data/regional-offices/east_midlands.yml, assets/data/regional-offices/london.yml, assets/data/regional-offices/north_west.yml, assets/data/regional-offices/south_east.yml, assets/data/regional-offices/south_west.yml, assets/data/regional-offices/west_midlands.yml, test/unit/services/email/index.js
=> Update email addresses for office-finder

apps/contact-ukti/fields/enquiry-reason.js, apps/contact-ukti/steps.js, apps/contact-ukti/translations/src/en/fields.json, assets/js/index.js, assets/js/modules/select-radio-via-hash.js, assets/scss/_shame.scss, config.js, services/email/index.js, test/unit/services/email/index.js
This is being actioned for this story https://trello.com/c/qCfx1640/294-updates-to-contact-form
=> Adding Getting Finance help button with new contact email

assets/data/regional-offices/east_midlands.yml, assets/data/regional-offices/north_west.yml
This ticket: https://trello.com/c/NE24xYHO/827-1-update-contact-us-form-with-new-addresses
Two addresses need to be updated on the ‘Contact Us’ form https://www.contactus.trade.gov.uk/office-finder/. 
See below: 
DIT East Midlands
CHANGE
Innovation House
Derby
East Midlands
DE21 7BFaddress
To
The International Trade Centre
5 Merus Court
Meridian Business Park
Leicester
LE19 1RJ 
DIT North West
CHANGE
Churchgate House
56 Oxford Street
Manchester
M60 7HJ
To
Lee House
90 Great Bridgewater Street
Manchester
M1 5JW
=> Updating addresses

manifest.yml
This change doubles the resource allocated to the app in PaaS
=> Updated to increase memory and no of instances

assets/data/regional-offices/east_of_england.yml
=> (fix) updating DIT East office address

Procfile
to enable pipeline to work in CF Gov PaaS
=> update:  Procfile with node command
